#logging:
#  level:
#    com.clown: trace          #日志打印级别
#  #path/file互斥
#  path: /springboot/log       #在当磁盘下创建springboot文件夹,在springboot文件夹下创建log文件夹,在log文件夹能生成指定名字的spring.log文件
#  #file: springboot.log       #不指定路径,当前项目下生成日志文件
#  #file: G:/springboot.log    #指定日志生成的路径
#  pattern:
#    console: "%d{yyyy-MM-dd} >>> [%thread] >>> %-5level >>> %logger{50} >>> %msg%n"               #在控制台指定输出的日志格式
#    file: "%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} === %msg%n"                  #指定文件的日志输出格式

spring:
  profiles:
    active: prod
---
spring:
  profiles: dev
---
spring:
     profiles: prod
