spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-rabbitmq?seUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: '123456'
#jpa设置
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  #RabbitMQ配置
  rabbitmq:
    host: 192.168.25.133
    port: 5672
#Redis配置
  redis:
    host: 192.168.25.133