person:
  name: 张3
  age: 12
  boss: false
  birthday: 1993/10/20
  email: clown_coding@163.com
  map:
    k1: v1
    k2: v2
  list:
    - 李4
    - 王5
  dog:
    name: 旺财
    age: 12
people:
  name: 王二麻子
  list:
    - Chinese
    - Japanese
    - American
student:
  id: ${random.uuid}
  name: 铁蛋
  age: ${random.int}
  grade: ${123:蓝翔挖掘机大学三年二班}
  dog:
    name: ${student.name}
    age: ${random.int(10)}