spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-cache?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: '123456'
    schema:
    - classpath:sql/springboot-cache.sql
    initialization-mode: never
#mybatis配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.clown.cache.model
  mapper-locations: classpath:mybatis/mapper/*.xml
#logging配置
logging:
  level:
    com.clown.cache.mapper: debug