management:
# 修改访问端点端口号
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
# 修改访问路径
#     base-path: /management
# 可关闭应用
  endpoint:
    shutdown:
      enabled: true

#设置Git信息
#spring:
#  info:
#    git:
#      location: classpath:git.properties