server:
  port: 9001
spring:
  application:
    name: springboot-mybatis-plus
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-mybatis-plus?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
##logging配置
#logging:
#  level:
#    com.clown.mp.mapper: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
#    #驼峰下划线转换
#    db-column-underline: true
#    #主键 ID 策略类型
#    id-type: 0
#    #全局表前缀 tb_
    table-prefix: tb_
  mapper-locations: classpath:/mapper/*mapper.xml